"""Residual-stream activations at last_prompt, first5 and response, one forward pass per row.

Input rows have id, messages, response, and live in generations/<model name>/<training|evaluation|judging>/,
directly or in subdirectories.
Writes <input stem>_activations.npz next to the input: arrays <position>_L<layer> of shape (n, hidden),
plus per-row id, n_tokens, prompt_len, n_response_tokens, first5_text, and
  contrastive inputs: label, polarity, pair_index, cell, pair_type, prompt_id
  judging inputs: benchmark, group (skyline split group), truncated, and if judged labels__<name> (int8, -1 = None)
Skipped rows are listed in the .meta.json.

Run from the repo root: python -m probe_training.get_activations --model ... --input ...
"""
import argparse
import hashlib
from collections import Counter
from pathlib import Path

import numpy as np

from utils.activations import LABEL_PREFIX, NO_LABEL, POSITIONS, extract, prepare, resolve_layers
from utils.io import REPO_ROOT, check_counts, read_jsonl, write_meta
from utils.models import load_model_and_tokenizer, text_config

SPLITS = ("training", "evaluation", "judging")
CONTRASTIVE_FIELDS = ("label", "polarity", "pair_index", "cell", "pair_type", "prompt_id")


def skyline_group(row: dict) -> str:
    """Rows sharing a group must share a side of a skyline split: AYS by question, ELEPHANT by prompt text."""
    if row["benchmark"] == "are_you_sure":
        text = row["question"]
    elif row["benchmark"] == "elephant":
        if row["messages"][0]["role"] != "user":
            raise ValueError(f"{row['id']}: first message is not the user prompt")
        text = row["messages"][0]["content"]
    else:
        raise ValueError(f"{row['id']}: no group rule for benchmark {row['benchmark']!r}")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def judging_fields(rows: list[dict]) -> dict[str, np.ndarray]:
    """Per-row benchmark, group, truncated and, if the rows are judged, one labels__<name> array per label."""
    fields = {
        "benchmark": np.array([r["benchmark"] for r in rows]),
        "group": np.array([skyline_group(r) for r in rows]),
        "truncated": np.array([r["truncated"] for r in rows], dtype=bool),
    }
    if not any("labels" in r for r in rows):
        return fields
    names = sorted(rows[0]["labels"])
    for r in rows:
        if sorted(r["labels"]) != names:
            raise ValueError(f"{r['id']}: label names {sorted(r['labels'])} differ from {names}")
    for name in names:
        values = []
        for r in rows:
            v = r["labels"][name]
            if v is None:
                values.append(NO_LABEL)
            elif v in (0, 1) and not isinstance(v, bool):
                values.append(v)
            else:
                raise ValueError(f"{r['id']}: label {name}={v!r} is not 0, 1 or None")
        fields[LABEL_PREFIX + name] = np.array(values, dtype=np.int8)
    return fields


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", required=True)
    parser.add_argument("--input", type=Path, required=True)
    layer_group = parser.add_mutually_exclusive_group(required=True)
    layer_group.add_argument("--layers", type=int, nargs="+", help="0-based block indices.")
    layer_group.add_argument("--layer-fracs", type=float, nargs="+", help="Depth fractions, round(frac * n_layers).")
    parser.add_argument("--max-length", type=int, required=True, help="Rows with more tokens are skipped, not truncated.")
    parser.add_argument("--batch-size", type=int, required=True)
    args = parser.parse_args()

    parts = args.input.resolve().relative_to(REPO_ROOT / "generations").parts  # raises if outside generations/
    if len(parts) < 3 or parts[1] not in SPLITS:
        raise ValueError(f"{args.input} is not under generations/<model>/<{'|'.join(SPLITS)}>/")
    model_dir, split = parts[0], parts[1]
    if model_dir != args.model.split("/")[-1]:
        raise ValueError(f"{args.input} was generated by {model_dir}, not {args.model}")
    out_path = args.input.resolve().parent / f"{args.input.stem}_activations.npz"

    rows = read_jsonl(args.input)
    ids = [r["id"] for r in rows]
    if len(set(ids)) != len(ids):
        raise ValueError(f"{args.input}: duplicate ids")

    model, tokenizer = load_model_and_tokenizer(args.model, padding_side="right")
    n_layers = text_config(model.config).num_hidden_layers
    layers = resolve_layers(n_layers, args.layers, args.layer_fracs)
    print(f"{args.model}: {n_layers} blocks; extracting blocks {layers} from hidden_states[L + 1]")

    prepared, skips = prepare(rows, tokenizer, args.max_length)
    if not prepared:
        raise ValueError(f"{args.input}: every row was skipped ({Counter(s['reason'] for s in skips)})")
    print(f"{len(prepared)} rows, {len(skips)} skipped")
    arrays = extract(model, tokenizer, prepared, layers, args.batch_size)

    # Pair fields and judged labels are kept so probes need not re-join the JSONL.
    by_id = {r["id"]: r for r in rows}
    kept = [by_id[p["id"]] for p in prepared]
    row_fields = {}
    if "label" in rows[0]:
        row_fields = {k: np.array([r[k] for r in kept]) for k in CONTRASTIVE_FIELDS}
    if split == "judging":
        row_fields = judging_fields(kept)
    np.savez(
        out_path,
        **arrays,
        **row_fields,
        id=np.array([p["id"] for p in prepared]),
        n_tokens=np.array([p["n_tokens"] for p in prepared]),
        prompt_len=np.array([p["prompt_len"] for p in prepared]),
        n_response_tokens=np.array([p["resp_end"] - p["prompt_len"] for p in prepared]),
        first5_text=np.array([p["first5_text"] for p in prepared]),
    )
    counts = check_counts(len(rows), Counter(s["reason"] for s in skips), len(prepared), args.input.name)
    extra = {
        "model": args.model,
        "n_layers": n_layers,
        "layers": layers,
        "layer_convention": "hidden_states[layer + 1]",
        "positions": list(POSITIONS),
        "dtype": "float32",
        "skips": skips,
    }
    if split == "judging":
        labels = {k[len(LABEL_PREFIX):]: v for k, v in row_fields.items() if k.startswith(LABEL_PREFIX)}
        extra["label_counts"] = {n: {"pos": int((y == 1).sum()), "neg": int((y == 0).sum()), "none": int((y == NO_LABEL).sum())}
                                 for n, y in labels.items()}
    write_meta(out_path, [args.input], args, counts, extra)
    print(f"Wrote {out_path}: {counts}")


if __name__ == "__main__":
    main()
