"""Fit one probe per pair x position x layer x method on the split's train prompts; report held-out metrics.

For each slug writes `<out-dir>/<slug>.probes.npz` and `<slug>.metrics.jsonl`.
"""
import argparse
from collections import Counter
from pathlib import Path

import numpy as np

from utils import probes
from utils.activations import POSITIONS, act_key, load_index
from utils.contrastive import DROP_REASONS, POLARITIES, load_pairs
from utils.io import check_counts, meta_path, read_json, read_jsonl, write_jsonl, write_meta
from utils.splits import split_masks


def load_pair_rows(slug: str, gen_path: Path, act_dir: Path):
    """Rows aligned to activation rows, after dropping whole prompts. Returns (kept index rows, row lookup, counts)."""
    rows = {r["id"]: r for r in read_jsonl(gen_path)}
    index, skips = load_index(act_dir, slug, list(rows))

    own_reason = {s["id"]: f"extraction_{s['reason']}" for s in skips}
    for r in rows.values():
        if r["degenerate"] in DROP_REASONS and r["id"] not in own_reason:
            own_reason[r["id"]] = f"degenerate_{r['degenerate']}"
    bad_prompts = {rows[i]["prompt_id"] for i in own_reason}
    excluded = Counter(own_reason.values())
    excluded["pair_partner_dropped"] = sum(
        1 for r in rows.values() if r["prompt_id"] in bad_prompts and r["id"] not in own_reason
    )
    kept = [i for i in index if rows[i["id"]]["prompt_id"] not in bad_prompts]
    counts = check_counts(len(rows), excluded, len(kept), slug)

    per_prompt = Counter(rows[i["id"]]["prompt_id"] for i in kept)
    if set(per_prompt.values()) - {len(POLARITIES)}:
        raise AssertionError(f"{slug}: some kept prompts do not have exactly one row per polarity")
    return kept, rows, counts


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pairs", type=Path, required=True)
    parser.add_argument("--slugs", nargs="+", required=True, help="Pair slugs, or 'all'.")
    parser.add_argument("--generations-dir", type=Path, required=True)
    parser.add_argument("--activations-dir", type=Path, required=True)
    parser.add_argument("--split", type=Path, required=True)
    parser.add_argument("--positions", nargs="+", choices=POSITIONS, required=True)
    parser.add_argument("--layers", type=int, nargs="+", required=True)
    parser.add_argument("--methods", nargs="+", choices=probes.METHODS, required=True)
    parser.add_argument("--C", type=float, required=True, help="Inverse L2 strength for logistic regression.")
    parser.add_argument("--max-iter", type=int, required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    args = parser.parse_args()

    pairs = load_pairs(args.pairs)
    slugs = list(pairs) if args.slugs == ["all"] else args.slugs
    split = read_json(args.split)
    if split["group_field"] != "prompt_id":
        raise ValueError(f"{args.split} groups by {split['group_field']!r}, expected prompt_id")
    args.out_dir.mkdir(parents=True, exist_ok=True)

    for slug in slugs:
        pair = pairs[slug]
        gen_path = args.generations_dir / f"{slug}.jsonl"
        npz_path = args.activations_dir / f"{slug}.npz"
        act_meta = read_json(meta_path(npz_path))
        missing_layers = sorted(set(args.layers) - set(act_meta["layers"]))
        if missing_layers:
            raise ValueError(f"{npz_path} lacks layers {missing_layers}")

        kept, rows, counts = load_pair_rows(slug, gen_path, args.activations_dir)
        gen_models = {r["model"] for r in rows.values()}
        if gen_models != {act_meta["model"]}:
            raise AssertionError(f"{slug}: generated by {sorted(gen_models)}, activations from {act_meta['model']}")
        act_rows = np.array([i["row"] for i in kept])
        y = np.array([rows[i["id"]]["label"] for i in kept], dtype=int)
        prompt_ids = [rows[i["id"]]["prompt_id"] for i in kept]
        tr, te = split_masks(prompt_ids, split)
        probes.check_binary(y[tr], f"{slug} train")
        print(f"[{slug}] {counts} | train {tr.sum()} / test {te.sum()}")

        fitted, metrics = {}, []
        with np.load(npz_path) as z:
            for position in args.positions:
                for layer in args.layers:
                    X = z[act_key(position, layer)][act_rows]
                    for method in args.methods:
                        probe = probes.fit(method, X[tr], y[tr], args.C, args.max_iter)
                        s = probes.score(method, probe, X[te])
                        win, n_pairs = probes.paired_win_rate(s, y[te], [p for p, m in zip(prompt_ids, te) if m])
                        fitted[probes.probe_key(method, position, layer)] = probe
                        metrics.append(
                            {
                                "source": "contrastive",
                                "target": slug,
                                "pair_type": pair["type"],
                                "method": method,
                                "position": position,
                                "layer": layer,
                                "split_seed": split["seed"],
                                "model": act_meta["model"],
                                "n_train": int(tr.sum()),
                                "n_test": int(te.sum()),
                                "n_test_pos": int(y[te].sum()),
                                "n_test_neg": int((y[te] == 0).sum()),
                                "holdout_auroc": probes.auroc(y[te], s),
                                "holdout_accuracy": probes.accuracy(y[te], s, method),
                                "holdout_paired_win_rate": win,
                                "n_test_pairs": n_pairs,
                            }
                        )
                        m = metrics[-1]
                        print(f"  {method:8s} {act_key(position, layer)}: auroc {m['holdout_auroc']} acc {m['holdout_accuracy']:.3f}")

        probes_path = args.out_dir / f"{slug}.probes.npz"
        metrics_path = args.out_dir / f"{slug}.metrics.jsonl"
        probes.save_probes(probes_path, fitted)
        write_jsonl(metrics_path, metrics)
        inputs = [args.pairs, gen_path, npz_path, args.split]
        extra = {"model": act_meta["model"], "split_seed": split["seed"]}
        for out in (probes_path, metrics_path):
            write_meta(out, inputs, args, counts, extra)


if __name__ == "__main__":
    main()
